### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by officialdrafty** [rwieruch/react-redux-soundcloud#4]
I'm on the step of the tutorial that talks about 'npm test' but when type in command lines give me Error Message that says: "SyntaxError: Unexpected token import".

`brandonpowell@Brandons-iMac ~/D/k/kdrusha-website-v2> npm test

> kdrusha-website-v2@0.1.0 test /Users/brandonpowell/Desktop/kdrusha-website-v1/kdrusha-website-v2
> mocha --compilers js:babel-core/register --require ./src/test/setup.js 'src/**/*spec.js'

/Users/brandonpowell/Desktop/kdrusha-website-v1/kdrusha-website-v2/src/test/setup.js:1
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at loader (/Users/brandonpowell/Desktop/kdrusha-website-v1/kdrusha-website-v2/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/brandonpowell/Desktop/kdrusha-website-v1/kdrusha-website-v2/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/brandonpowell/Desktop/kdrusha-website-v1/kdrusha-website-v2/node_modules/mocha/bin/_mocha:345:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/brandonpowell/Desktop/kdrusha-website-v1/kdrusha-website-v2/node_modules/mocha/bin/_mocha:344:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
npm ERR! Test failed.  See above for more details.`

`import React from 'react';
import { expect } from 'chai';
import jsdom from 'jsdom';

const doc = jsdom.jsdom('<!doctype html><html><body></body></html>');
const win = doc.defaultView;

global.document = doc;
global.window = win;

Object.keys(window).forEach((key) => {
  if (!(key in global)) {
    global[key] = window[key];
  }
});

global.React = React;
global.expect = expect;
`

**Comment by 3fernandez** [comment]
Hi @brandonpowell,

I also followed this tutorial and didn't experienced this **SyntaxError** in the specified section. Maybe you structured your code differently. But, I noticed in your error log that you're calling the test config file _"setup.js"_ from the _"src/test"_ folder, while in the tutorial the _"test"_ folder was created in the root.
